import { ITextGenerator, AIContent } from '../types';

export class ClaudeAdapter implements ITextGenerator {
    private apiKey: string;

    constructor(apiKey: string) {
        this.apiKey = apiKey;
    }

    async generateContent(prompt: string): Promise<AIContent> {
        console.log(`[Claude] Generating content for: "${prompt}"...`);

        if (!this.apiKey) {
            throw new Error("Claude API Key is required");
        }

        // System Prompt to ensure output matches expected JSON structure and SSML requirements
        const systemPrompt = `
            You are a creative director and screenwriter for short video content.
            Output purely valid JSON. No markdown backticks.
            
            Structure:
            {
                "script": "Narration text here...",
                "imagePrompt": "Detailed image generation prompt...",
                "keywords": ["keyword1", "keyword2"]
            }

            IMPORTANT:
            1. For 'script', you MUST use SSML tags for pacing.
               - Use <break time='1.0s' /> between distinct scenes or thoughts.
               - Use <break time='0.5s' /> for dramatic pauses or commas.
               - Example: "Welcome to the future. <break time='1.0s' /> Robots are everywhere."
            2. For 'imagePrompt', describe a cinematic scene in high detail (lighting, camera, style).
        `;

        // TODO: Replace with actual Anthropic SDK call
        // const response = await anthropic.messages.create({ ... });

        // Mock return for skeleton flow (Video generation can proceed even without real API if we return valid structure)
        return {
            script: "This is a script generated by Claude. <break time='0.5s' /> It includes SSML tags for Gemini TTS.",
            imagePrompt: "Cinematic shot of a glowing AI interface, cyberpunk style, neon blue and magenta lighting, 8k.",
            keywords: ["claude", "ai", "test"]
        };
    }
}
